"""Correcao nome de tabela carrinho

Revision ID: e63b24dcfff9
Revises: b45ea2bc219e
Create Date: 2026-02-28 12:22:28.541967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e63b24dcfff9'
down_revision: Union[str, Sequence[str], None] = 'b45ea2bc219e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itensCarrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itensCarrinho_id'), 'itensCarrinho', ['id'], unique=False)
    op.drop_index(op.f('ix_carrinhos_id'), table_name='carrinhos')
    op.drop_table('carrinhos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrinhos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('produto_id', sa.INTEGER(), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=True),
    sa.Column('criado_em', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrinhos_id'), 'carrinhos', ['id'], unique=False)
    op.drop_index(op.f('ix_itensCarrinho_id'), table_name='itensCarrinho')
    op.drop_table('itensCarrinho')
    # ### end Alembic commands ###
